{
  name: "bin",
  version: "1.0.0",
  description: "help wanted",
  main: "cleanInstall.js",
  scripts": {
  echo: '"#Hello-🌍!'"''
  },
  Author: '"zachryiixixiiwood@gmail.com/MOEJOJOJOJO'@.GIT.IT'"'',
  license: '"IBM'"'',
  async": "repo'Dync={data'@1.mvm,-repo' sync,'@ZachryTylerWood'@Administrator'@.git.it/git.github.com/gists'"''",
  Gracehopper:  "4.1.11
  prettier: :"1.12.1
  grunt: 1.0.0
list: '"dependencies'"''
 - 
}
