#!/bin/bash
home=`pwd`
modules=('blueocean-dashboard' 'blueocean-personalization' 'blueocean-web')
for i in "${modules[@]}"; do
 cd $i; ncu -a; rm -rf node_modules npm-shrinkwrap.json; npm i; npm shrinkwrap; cd $home
done
