node {

    stage("parallel") {
      parallel firstBranch: {
          echo 'first branch visible'
          sh 'ping -c 30 localhost'

      }, secondBranch: {
          echo 'second branch visible'
          sh 'ping -c 30 localhost'
      }

    }

}
