export {
    buildOrganizationUrl,
    buildPipelineUrl,
    rootPath,
    buildClassicConfigUrl,
    buildClassicInputUrl,
    buildClassicBuildUrl,
    buildRunDetailsUrl,
    doubleUriEncode,
    fetchAllSuffix,
    applyFetchAll,
    calculateFetchAll,
    calculateLogView,
    calculateLogUrl,
    calculateNodeBaseUrl,
    calculateStepsBaseUrl,
    calculateRunLogURLObject,
    paginateUrl,
    endSlash,
    getRestUrl,
    buildUrl,
    relativeUrl,
} from '@jenkins-cd/blueocean-core-js';

// FIXME-JM: This is an abomination. Individual files within Dashboard should import from core-js, which needs to have all its URL utils collapsed into one module
