pipeline {
  agent any
  triggers {
    upstream(upstreamProjects: 'upstreamJob', threshold: hudson.model.Result.SUCCESS)
  }
  stages {
    stage('Example') {
      steps {
        echo 'Hello World'
      }
    }
  }
}
